---
# tasks file for mysql
- name: Installing the MySQL packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
   - mariadb-common
   - mariadb-server
   - mariadb-client
   - python-mysqldb


- name: Updating MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} state=present
  with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

- name: Copying the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

- name: Ensuring Anonymous user(s) are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
        - localhost
        - "{{ ansible_hostname }}"

- name: Removing the test database
  mysql_db: name=test state=absent
  notify:
        - Restart MySQL