---
- name: Configure application
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: common
    - role: apache
    - role: mysql
    - role: php
    - role: phpmyadmin
    - role: joomla